{
 "title": "ADX analytics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "storeDB",
     "expression": {
      "from": { "property": { "name": "bronzeOrders", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let imp = \nimpressions\n| where $__timeFilter(impressionDate)\n| extend dateOnly = substring(todatetime(impressionDate).tostring(), 0, 10)\n| summarize imp_count = count() by dateOnly;\nlet clck = \nclicks\n| where $__timeFilter(clickDate)\n| extend dateOnly = substring(todatetime(clickDate).tostring(), 0, 10)\n| summarize clck_count = count() by dateOnly;\nimp \n| join clck on $left.dateOnly == $right.dateOnly\n| project selected_date = dateOnly , impressions = imp_count , clicks = clck_count, CTR = clck_count * 100 / imp_count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Impressions by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "storeDB",
     "expression": {
      "from": { "property": { "name": "bronzeOrders", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "impressions\n| where $__timeFilter(impressionDate)\n| join external_table('products') on $left.productId == $right.ProductID",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Page Max load time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "storeDB",
     "expression": {
      "from": { "property": { "name": "bronzeOrders", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "impressions\n| where $__timeFilter(impressionDate)\n| summarize load_time_max = max(page_loading_seconds) by bin(impressionDate, 1d)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Clicks by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "storeDB",
     "expression": {
      "from": { "property": { "name": "bronzeOrders", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "clicks\n| where $__timeFilter(clickDate)\n| join external_table('products') on $left.productId == $right.ProductID",
     "querySource": "raw"
    }
   ]
  }
 ]
}